// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdUfoq0JA5OI7LSJWRXPsdYTVCsp-KNKo',
    appId: '1:557548135367:web:641d2d1e48a036d99fafe2',
    messagingSenderId: '557548135367',
    projectId: 'tech-service-app-e9ade',
    authDomain: 'tech-service-app-e9ade.firebaseapp.com',
    storageBucket: 'tech-service-app-e9ade.firebasestorage.app',
    measurementId: 'G-PX5XNPLQKD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdUfoq0JA5OI7LSJWRXPsdYTVCsp-KNKo',
    appId: '1:557548135367:android:ca56dccecaf4f22c9fafe2',
    messagingSenderId: '557548135367',
    projectId: 'tech-service-app-e9ade',
    storageBucket: 'tech-service-app-e9ade.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdUfoq0JA5OI7LSJWRXPsdYTVCsp-KNKo',
    appId: '1:557548135367:ios:ca56dccecaf4f22c9fafe2',
    messagingSenderId: '557548135367',
    projectId: 'tech-service-app-e9ade',
    storageBucket: 'tech-service-app-e9ade.firebasestorage.app',
    iosBundleId: 'com.techservice.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdUfoq0JA5OI7LSJWRXPsdYTVCsp-KNKo',
    appId: '1:557548135367:ios:ca56dccecaf4f22c9fafe2',
    messagingSenderId: '557548135367',
    projectId: 'tech-service-app-e9ade',
    storageBucket: 'tech-service-app-e9ade.firebasestorage.app',
    iosBundleId: 'com.techservice.app',
  );
}
